#include "command_code.h"




COMMAND_DEFINE(EXIT, 0, CMD_EXIT_CODE, 0)
COMMAND_DEFINE(PUSH, 1, CMD_PUSH_CODE, 1)
COMMAND_DEFINE(POP, 2, CMD_POP_CODE, 1)
COMMAND_DEFINE(ADD, 3, CMD_ADD_CODE, 2)
COMMAND_DEFINE(JMP, 4, CMD_JMP_CODE, 1)
COMMAND_DEFINE(JE, 5, CMD_JE_CODE, 1)
COMMAND_DEFINE(JNE, 6, CMD_JNE_CODE, 1)
COMMAND_DEFINE(JG, 7, CMD_JG_CODE, 1)
COMMAND_DEFINE(JGE, 8, CMD_JGE_CODE, 1)
COMMAND_DEFINE(JL, 9, CMD_JL_CODE, 1)
COMMAND_DEFINE(JLE, 10, CMD_JLE_CODE, 1)
COMMAND_DEFINE(IN, 11, CMD_IN_CODE, 0)
COMMAND_DEFINE(OUT, 12, CMD_OUT_CODE, 0)
COMMAND_DEFINE(CMP, 13, CMD_CMP_CODE, 2)
COMMAND_DEFINE(DEC, 14, CMD_DEC_CODE, 0)
COMMAND_DEFINE(INC, 15, CMD_INC_CODE, 0)
COMMAND_DEFINE(CALL, 16, CMD_CALL_CODE, 1)
COMMAND_DEFINE(RTN, 17, CMD_RTN_CODE, 0)

