#include "command_code.h"

COMMAND_DEFINE(EXIT, 0, CMD_EXIT_CODE, 0)
COMMAND_DEFINE(PUSH, 1, CMD_PUSH_CODE, 1)
COMMAND_DEFINE(POP, 2, CMD_POP_CODE, 1)
COMMAND_DEFINE(ADD, 3, CMD_ADD_CODE, 0)
COMMAND_DEFINE(JMP, 4, CMD_JMP_CODE, 1)
COMMAND_DEFINE(IN, 5, CMD_IN_CODE, 0)
COMMAND_DEFINE(OUT, 6, CMD_OUT_CODE, 0)